FROM resin/%%RESIN_MACHINE_NAME%%-debian

ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq --no-install-recommends \
	cron \
	rsnapshot \
	openssh-client \
	curl \
	&& apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir /root/.ssh \
	&& chmod 700 /root/.ssh

COPY ssh_config.txt /root/.ssh/config

RUN chmod 600 /root/.ssh/config

COPY crontab.txt ./

RUN crontab crontab.txt

WORKDIR /usr/src/app

COPY /app ./

CMD ["/bin/bash", "start.sh"]