version: '2.1'

volumes:

  ssh-data:

services:

  rsnapshot:
    image: klutchell/rsnapshot:armhf-0.0.16
    privileged: true
    volumes:
      - 'ssh-data:/root/.ssh'

  ssh:
    image: klutchell/ssh:armhf-0.0.13
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'

