version: '2.1'

volumes:

  ssh-data:

services:

  rsnapshot:
    image: klutchell/rsnapshot:armhf-0.0.16
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/sda
    volumes:
      - 'ssh-data:/root/.ssh'

  ssh:
    image: klutchell/ssh:armhf-0.0.14
    privileged: true
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'

