version: '2.1'

volumes:

  ssh-data:

services:

  rsnapshot:
    image: klutchell/rsnapshot:rpi3-latest
    privileged: true
    volumes:
      - 'ssh-data:/root/.ssh'

  ssh:
    image: klutchell/ssh:rpi3-a0b03c9
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'

