FROM armhf/alpine

LABEL maintainer="kylemharding@gmail.com"

ENV SNAPSHOT_ROOT /snapshots

RUN apk add --no-cache \
	curl \
	dcron \
	rsnapshot \
	openssh-client \
	tzdata

COPY . /usr/src/app/
WORKDIR /usr/src/app

RUN sed -r \
	-e "s|^#?(snapshot_root\s+.+)$|snapshot_root\t$SNAPSHOT_ROOT/|" \
	-e "s/^#?(no_create_root\s+.+)$/no_create_root\t1/" \
	-e "s/^#?(cmd_ssh\s+.+)$/\1/" \
	-e "s/^#?(cmd_cp\s+.+)$/\1/" \
	-e "s/^#?(retain\s+(alpha|hourly)\s+.+)$/retain\talpha\t6/" \
	-e "s/^#?(retain\s+(beta|daily)\s+.+)$/retain\tbeta\t7/" \
	-e "s/^#?(retain\s+(gamma|weekly)\s+.+)$/retain\tgamma\t4/" \
	-e "s/^#?(retain\s+(delta|monthly)\s+.+)$/retain\tdelta\t3/" \
	-e "s/^#?(backup\s+.+)$/#\1/" \
	-e "s/^#?(backup_script\s+.+)$/#\1/" \
	/etc/rsnapshot.conf.default > /usr/src/app/rsnapshot.conf

RUN rm /etc/crontabs/root \
	&& ln -s /usr/src/app/crontab /etc/crontabs/root

VOLUME $SNAPSHOT_ROOT

# run start script on boot
CMD ["/bin/ash", "start.sh"]

